# Basic Site Settings
title: "Decadent Heroism"
name: &name "Jackson Paslay"
description: &description "Jackson Paslay's Website"
url: "https://actionjacksoncodes.github.io"
baseurl: ""  # MUST be empty for a user page
remote_theme: "academicpages/academicpages"
repository: "https://github.com/actionjacksoncodes/actionjacksoncodes.github.io"

# Author
author:
  avatar: "wtwtw.jpg"
  name: "Jackson Paslay"
  pronouns: "they/them/he/him"
  bio: "Short biography for your sidebar"
  location: "Sioux Falls, South Dakota and Potsdam, Germany"
  university: "Augustana University"
  uri: "https://actionjacksoncodes.github.io"
  email: "jpaslay22@ole.augie.edu"
  bluesky: "bsky.app"
  twitter: ""
  instagram: ""
  soundcloud: ""
  academia.edu: ""

# Collections, plugins, defaults, etc.
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# ...and all your other previous settings
