# -------------------------
# Basic Site Settings
# -------------------------
title: "Decadent Heroism"
name: &name "Jackson Paslay"
description: &description "Jackson Paslay's academic portfolio"
url: "https://decadentheroism.github.io"
baseurl: "decadentheroism.github.io/blog"  # leave empty for user pages
remote_theme: "academicpages/academicpages"
repository: "https://github.com/decadentheroism/decadentheroism.github.io"
locale: "en-US"

# -------------------------
# Author
# -------------------------
author:
  avatar: "wtwtw.jpg"
  name: "Jackson Paslay"
  pronouns: "they/them/he/him"
  bio: "Short biography for your sidebar"
  location: "Sioux Falls, South Dakota and Potsdam, Germany"
  university: "Augustana University"
  uri: "https://decadentheroism.github.io"
  email: "jpaslay22@ole.augie.edu"

  # Social / Academic Profiles
  bluesky: "bsky.app"
  goodreads: ""
  instagram: ""
  soundcloud: ""
  tumblr: ""
  twitter: ""

# -------------------------
# Publication Categories
# -------------------------
publication_category:
  articles:
    title: "Essays"
  poems:
    title: "Poems"
  conferences:
    title: "Conference Papers"

# -------------------------
# Site Settings
# -------------------------
teaser: ""
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false

# -------------------------
# Comments
# -------------------------
comments:
  provider: ""
  disqus:
    shortname: ""
  discourse:
    server: ""
  facebook:
    appid: ""
    num_posts: 5
    colorscheme: "light"

staticman:
  allowedFields: ['name', 'email', 'url', 'message']
  branch: "gh-pages"
  commitMessage: "New comment."
  filename: comment-{@timestamp}
  format: "yml"
  moderation: true
  path: "_data/comments/{options.slug}"
  requiredFields: ['name', 'email', 'message']
  transforms:
    email: "md5"
  generatedFields:
    date:
      type: "date"
      options:
        format: "iso8601"

# -------------------------
# Feeds
# -------------------------
atom_feed:
  hide: false
  path: ""

# -------------------------
# SEO
# -------------------------
google_site_verification: ""
bing_site_verification: ""
alexa_site_verification: ""
yandex_site_verification: ""

twitter:
  username: ""
facebook:
  username: ""
  app_id: ""
  publisher: ""
og_image: ""
og_description: ""
social:
  type: ""
  name: ""
  links: []

analytics:
  provider: "false"
  google:
    tracking_id: ""

# -------------------------
# Include / Exclude Files
# -------------------------
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# -------------------------
# Markdown / Conversion
# -------------------------
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# -------------------------
# Collections
# -------------------------
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# -------------------------
# Defaults
# -------------------------
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# -------------------------
# Sass / SCSS
# -------------------------
sass:
  sass_dir: _sass
  style: compressed

# -------------------------
# Output
# -------------------------
permalink: /:categories/:title/
timezone: Etc/UTC

# -------------------------
# Plugins
# -------------------------
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# -------------------------
# Archives
# -------------------------
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# -------------------------
# HTML Compression
# -------------------------
compress_html:
  clippings: all
  ignore:
    envs: development
